### ISSUE TITLE
Your 1.18 build reports itself as 1.17 to the MCLink server

### ISSUE THREAD

**Issue by dries007** [ThatGamerBlue/MCLink-Fabric#1]
See this line:

https://github.com/ThatGamerBlue/MCLink-Fabric/blob/15f569e917aad0a2ef103837bc33aacdfb01f342/src/main/java/net/dries007/mclink/MCLink.java#L103

On another note: would you mind that I put this under the MCLink org on github? I can add you as contributer there so you we both can maintain it.
Then I can also put it on some official distribution channels & the website.

**Comment by ThatGamerBlue** [comment]
fixed in 3e868782902444cb662c06dffce65b83bbb0d6f5

feel free to move it over, ill archive this repo after it's migrated, thanks for making an awesome service
